export interface Article {
  slug: string;
  title: string;
  description: string;
  category: string;
  readMins: number;
  outline: string[];
  // Set true only once the full article body (1,500+ words) has replaced the
  // outline-only template. Unpublished articles are noindex'd and excluded
  // from the sitemap so Google never sees thin content.
  published?: boolean;
}

export const ARTICLES: Article[] = [
  { slug: 'top-devops-tools-2026', title: 'Top DevOps Tools in 2026: What Teams Actually Use', category: 'DevOps', readMins: 12, description: 'A practitioner-tested rundown of the CI/CD, IaC, observability and security tooling that real platform teams run in 2026.', outline: ['How we evaluated tools', 'CI/CD: GitHub Actions, GitLab, Argo', 'IaC: Terraform, OpenTofu, Pulumi', 'Observability: Prometheus, Grafana, OpenTelemetry', 'Security & supply chain', 'Choosing a stack by team size'] },
  { slug: 'kubernetes-troubleshooting-guide', title: 'Kubernetes Troubleshooting Guide: From CrashLoopBackOff to NotReady', category: 'Kubernetes', readMins: 15, description: 'A field guide to debugging pods, nodes, networking and storage in Kubernetes, with the exact kubectl commands to run at each step.', outline: ['Triage workflow', 'Pod failures: CrashLoopBackOff, OOMKilled, ImagePullBackOff', 'Node NotReady and kubelet issues', 'Service and DNS debugging', 'PVC and storage problems', 'Control plane health'] },
  { slug: 'linux-commands-for-devops', title: 'Linux Commands Every DevOps Engineer Should Know', category: 'Linux', readMins: 10, description: 'The 40 Linux commands that cover 95 percent of real production work: process, disk, network, and log investigation with examples.', outline: ['Process & load: top, ps, pidstat', 'Disk & IO: iostat, df, du, lsof', 'Network: ss, ip, tcpdump, curl', 'Logs: journalctl, grep, awk', 'One-liners worth memorizing'] },
  { slug: 'terraform-best-practices', title: 'Terraform Best Practices for Production Teams', category: 'Terraform', readMins: 11, description: 'State management, module design, workspaces vs directories, CI integration and policy checks for safe Terraform at scale.', outline: ['Repository layout', 'Remote state and locking', 'Module versioning', 'Plan in CI, apply with approval', 'Policy as code', 'Drift detection'] },
  { slug: 'docker-security-checklist', title: 'Docker Security Checklist: 20 Controls Before Production', category: 'Docker', readMins: 9, description: 'A concrete checklist covering image provenance, non-root users, secrets, capabilities, scanning and runtime hardening.', outline: ['Image hygiene', 'Build-time controls', 'Runtime hardening', 'Secrets management', 'Scanning and SBOMs'] },
  { slug: 'aws-cost-optimization-guide', title: 'AWS Cost Optimization Guide: Cut 30% Without Breaking Things', category: 'AWS', readMins: 13, description: 'Rightsizing, Savings Plans, storage tiering, data transfer traps and the FinOps habits that keep bills down month after month.', outline: ['Find the waste: Cost Explorer & CUR', 'Compute: rightsizing & Savings Plans', 'Storage tiering', 'Data transfer gotchas', 'Tagging & accountability'] },
  { slug: 'cron-syntax-explained', title: 'Cron Syntax Explained: Examples, Pitfalls and Debugging', category: 'Linux', readMins: 7, description: 'Master the five cron fields, special strings, step values and timezone behavior with copy-paste examples.', outline: ['The five fields', 'Special strings', 'Steps and ranges', 'Timezones & DST', 'Debugging missed runs'] },
  { slug: 'kubernetes-resource-requests-limits', title: 'Kubernetes Requests and Limits: A Practical Sizing Guide', category: 'Kubernetes', readMins: 10, description: 'How requests, limits and QoS classes interact with scheduling, eviction and OOM kills, and how to size them from real metrics.', outline: ['Requests vs limits', 'QoS classes', 'CPU throttling', 'Sizing from metrics', 'VPA and right-sizing'] },
  { slug: 'ci-cd-pipeline-design', title: 'CI/CD Pipeline Design Patterns That Scale', category: 'DevOps', readMins: 11, description: 'Trunk-based development, environment promotion, artifact immutability and rollback strategies for reliable delivery.', outline: ['Branching strategy', 'Build once, deploy many', 'Environment promotion', 'Rollbacks', 'Pipeline security'] },
  { slug: 'nginx-vs-haproxy', title: 'NGINX vs HAProxy: Choosing a Load Balancer in 2026', category: 'Networking', readMins: 9, description: 'Performance, configuration model, observability and TLS handling compared, with guidance on when each one wins.', outline: ['Architecture differences', 'L4 vs L7 features', 'Performance benchmarks', 'Config & ops experience', 'Decision matrix'] },
  { slug: 'prometheus-alerting-best-practices', title: 'Prometheus Alerting Best Practices: Fewer Pages, Better Signals', category: 'Observability', readMins: 10, description: 'Symptom-based alerting, burn-rate SLOs, label hygiene and routing patterns that cut alert fatigue.', outline: ['Symptoms over causes', 'SLO burn rates', 'Label hygiene', 'Routing & silences', 'Runbook links'] },
  { slug: 'gitops-with-argocd', title: 'GitOps with Argo CD: From Zero to Production', category: 'Kubernetes', readMins: 12, description: 'Set up Argo CD with app-of-apps, sync waves, secrets handling and multi-cluster patterns.', outline: ['GitOps principles', 'Install & RBAC', 'App-of-apps', 'Secrets strategies', 'Multi-cluster'] },
  { slug: 'bash-scripting-patterns', title: 'Bash Scripting Patterns for Reliable Automation', category: 'Linux', readMins: 9, description: 'Strict mode, traps, argument parsing, logging and testing patterns that keep shell scripts maintainable.', outline: ['set -euo pipefail', 'Traps & cleanup', 'getopts', 'Logging', 'Testing with bats'] },
  { slug: 'vpc-design-aws', title: 'AWS VPC Design: Subnets, Routing and Multi-AZ Patterns', category: 'AWS', readMins: 11, description: 'CIDR planning, public/private subnet tiers, NAT strategies, endpoints and hub-spoke designs explained with diagrams.', outline: ['CIDR planning', 'Subnet tiers', 'NAT & egress', 'VPC endpoints', 'Hub-spoke & TGW'] },
  { slug: 'incident-response-runbook', title: 'Building an Incident Response Runbook That People Actually Use', category: 'SRE', readMins: 8, description: 'Severity definitions, roles, communication templates and postmortem structure for calm, fast incident handling.', outline: ['Severity matrix', 'Roles', 'Comms templates', 'Timeline keeping', 'Blameless postmortems'] },
  { slug: 'helm-chart-best-practices', title: 'Helm Chart Best Practices: Values, Templates and Testing', category: 'Kubernetes', readMins: 10, description: 'Values schema design, template helpers, library charts and chart testing for maintainable Helm releases.', outline: ['Values design', 'Helpers & partials', 'Schema validation', 'helm test & ct', 'Versioning'] },
  { slug: 'ssh-hardening-guide', title: 'SSH Hardening Guide for Production Servers', category: 'Security', readMins: 8, description: 'Key-only auth, sshd_config hardening, certificates, bastions and session auditing for secure access.', outline: ['Disable passwords', 'sshd_config settings', 'SSH certificates', 'Bastion patterns', 'Auditing'] },
  { slug: 'log-management-strategy', title: 'Log Management Strategy: From rsyslog to Elasticsearch', category: 'Observability', readMins: 12, description: 'Designing an ingestion pipeline with rsyslog, Kafka buffering, parsers and Elasticsearch sizing for high-volume logs.', outline: ['Pipeline architecture', 'Buffering with Kafka', 'Parsing & enrichment', 'ES sizing & ILM', 'Cost control'] },
  { slug: 'zero-downtime-deployments', title: 'Zero-Downtime Deployments: Rolling, Blue-Green and Canary', category: 'DevOps', readMins: 9, description: 'How each strategy works, what it costs, and how health checks and connection draining make or break it.', outline: ['Rolling updates', 'Blue-green', 'Canary & metrics', 'Draining & readiness', 'Choosing a strategy'] },
  { slug: 'iam-least-privilege', title: 'IAM Least Privilege in Practice: A Step-by-Step Method', category: 'AWS', readMins: 10, description: 'Use Access Analyzer, CloudTrail data and permission boundaries to shrink IAM policies without breaking workloads.', outline: ['Start from activity', 'Access Analyzer', 'Permission boundaries', 'SCPs', 'Continuous review'] },
];

export const getArticle = (slug: string) => ARTICLES.find((a) => a.slug === slug);
